metadata:
  favicon: ''
  title: Logistics Dashboard
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
  vibeAppPhase: impl
  vibeAppAutoApplyMigrations: true
  vibeAppConnectedDatasources:
    - afghco_shipping_logistics
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
  hideRenderCachingSettings: false
internalType: vibe_project
id: GfQOROLsKr
